import fs from 'fs';
import { neon } from '@neondatabase/serverless';
process.env.DATABASE_URL = fs.readFileSync('/tmp/dburl','utf8').trim();
const { initializeDatabase } = await import('/home/wuying/.accio/accounts/1782137317/agents/MID-16137317U1786491-DFB0B8-4031-424044/project/web/lib/database.test.mjs');
await initializeDatabase();
const sql = neon(process.env.DATABASE_URL);
const c = await sql('SELECT COUNT(*) AS cnt FROM bot_commands');
const aliased = await sql("SELECT name, aliases FROM bot_commands WHERE aliases::text <> '[]' LIMIT 3");
console.log('count after seed:', c[0].cnt);
console.log('sample with aliases:', JSON.stringify(aliased));
process.exit(0);
